/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package cardgame;

import java.util.ArrayList;
import java.util.Scanner;

import cardgame.entity.Card;
import cardgame.entity.Deck;
import cardgame.entity.Player;
import cardgame.service.GameService;

public class App {
   

    public static void main(String[] args) {

        Scanner scanner = new Scanner(System.in);
        boolean playAgain = true;
        Deck deck;
        ArrayList<Player> players;
        int numPlayers;
        do{
            deck = new Deck();
            deck.shuffle();
            players = new ArrayList<>();

            System.out.print("\n    Enter the number of players (2-4): \n"); 
            numPlayers = scanner.nextInt();

            if(numPlayers <=4 && numPlayers >=2){
                for (int i = 1; i <= numPlayers; i++) {
                    System.out.println("    Enter Player"+ i +" name : ");
                    String name = scanner.next();

                    Player player = new Player(name);
                    for (int j = 0; j < 5; j++) {
                        Card card = deck.deal();
                        player.draw(card);
                    }
                    players.add(player);
                }

                GameService game = new GameService(players, deck);
                game.playGame();
            }
            else {
                System.out.println("\n    Enter valid number of player (i.e. 2,3,4)");
            }

            System.out.println("\n\n    Do you want to play again (yes/no)");
            String string = scanner.next();
            if(!string.equalsIgnoreCase("yes")){
                System.out.print("\n    Thanks for Playing the Game ");
                players.forEach(pl -> System.out.print(pl));
                System.out.println();
                playAgain = false;
            }


        }while(playAgain);
        

        scanner.close();
            
    }
}
